### ISSUE TITLE
Odd safari UA not supported

### ISSUE THREAD

**Issue by thashimalayaratnam** [3rd-Eden/useragent#104]
The user agent string `Safari/12602.4.8 CFNetwork/807.2.14 Darwin/16.4.0 (x86_64)` seems to not be recognized as a valid browser. 

This has also been reported in another detection library: https://github.com/bestiejs/platform.js/issues/124

**Comment by 3rd-Eden** [comment]
Cfnetwork isnt a browser; https://developer.apple.com/library/content/documentation/Networking/Conceptual/CFNetwork/Introduction/Introduction.html

**Comment by thashimalayaratnam** [comment]
Ah okay, thanks.
