### ISSUE TITLE
Mac device recognized as other

### ISSUE THREAD

**Issue by yellowandy** [3rd-Eden/useragent#34]
Hi,  thanks for the great module, really enjoy it.  Quick question, the following UA string:

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.65 Safari/537.36',

results in the device being set to 'Other', what are your thoughts about it containing Macintosh or Desktop since that is the 'device' the user is actually using?

**Comment by sourcec0de** [comment]
This seems to have regressed as of `2.2.1`

**Comment by LvChengbin** [comment]
I encountered the same problem
