### ISSUE TITLE
Wanted: isCrawler()

### ISSUE THREAD

**Issue by binarykitchen** [3rd-Eden/useragent#54]
For reasons similar as https://gist.github.com/Stanback/6998085 I would love to see an `isCrawler()` function in this package, so that I can code some special exceptions in my single page app.

Thanks!

**Comment by megadrojatel** [comment]
I would like to use this module, but i need isCrowler too.Are the function planned to enter in future versions?

Thanks

**Comment by blimmer** [comment]
This would be helpful for me, too. I think, for now you could use `family: 'Spider'`, right?

e.g.
```
> useragent.parse('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)').device.family === 'Spider'
true

> useragent.parse('Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)').device.family === 'Spider'
true
```

**Comment by binarykitchen** [comment]
yeah, something like that would be cool

**Comment by stevenvachon** [comment]
There is [isbot](https://npmjs.com/isbot), but I think this library would be more accurate.

**Comment by binarykitchen** [comment]
thx, yes it is
