### ISSUE TITLE
uap-core regexs.yaml

### ISSUE THREAD

**Issue by yunong** [3rd-Eden/useragent#59]
Is there a reason you're not using the regexes from uap-core (https://github.com/ua-parser/uap-core/blob/master/regexes.yaml)? It seems to be updated to keep pace with new UAs and the regexes this repo uses is using the old deprecated repo at https://raw.githubusercontent.com/tobie/ua-parser/master/regexes.yaml

**Comment by 3rd-Eden** [comment]
I didn't notice the relocation of the project, i'll update the internals and do a new release. Thanks for the notice.
