### ISSUE TITLE
invalid device when parsing android useragent (toString() = HTC Desire $2 $3 $4 A8181.0.0)

### ISSUE THREAD

**Issue by mrbar42** [3rd-Eden/useragent#81]
when parsing this user agent: 

`Mozilla/5.0 (Linux; U; Android 2.2; fr-fr; Desire_A8181 Build/FRF91) App3leWebKit/53.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`

the device is:
`HTC Desire $2 $3 $4 A8181.0.0`
or
{
     family: 'HTC Desire $2 $3 $4',
     major: 'A8181',
     minor: '0',
     patch: '0' }

seems like the regex groups wasn't replaced correctly

**Comment by steve-p-com** [comment]
Perhaps this is related to #63 which I think is still an issue, although it seems to happen less often than used to be the case. I also see $ variables in the device family for certain devices e.g.

```
Mozilla/5.0 (Linux; Android 4.4.2; en-gb; SAMSUNG SM-T230 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Safari/537.36
```

In this case, it produces ```Samsung $2```

In general, ```useragent``` works great though, so it's not a show stopper for us. It would be nice if it were fixed, and every now and then, I come here to see what's up :smile:
