### ISSUE TITLE
Won't parse iOS from CFNetwork user-agent string

### ISSUE THREAD

**Issue by ronkorving** [3rd-Eden/useragent#96]
User agent: `gcw/36 CFNetwork/711.3.18 Darwin/14.0.0`

Parse output:

```
> useragent.parse('gcw/36 CFNetwork/711.3.18 Darwin/14.0.0');
Agent {
  family: 'CFNetwork',
  major: '711',
  minor: '3',
  patch: '18',
  source: 'gcw/36 CFNetwork/711.3.18 Darwin/14.0.0' }
```

According to https://user-agents.me/operating-system/apple/ios-8 (and my device) this should be recognized as iOS 8.3.

**Comment by ronkorving** [comment]
Nevermind, it works! I just didn't quite understand how to extract the data from the agent (since the `os` property for example doesn't show up in the REPL).

**Comment by krin-san** [comment]
@ronkorving, do you have an offline copy of CFNetwork version list? The website you linked seems corrupted - redirects on the main page.

**Comment by ronkorving** [comment]
This was a year ago. I'm sorry I don't :(
